# Generated by Django 5.2.16 on 2026-07-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditbalance",
            name="max_portfolios",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_portfolios",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many portfolios a user on this plan can create.",
            ),
        ),
    ]
