# Generated by Django 5.2.16 on 2026-07-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("AGM", "Annual General Meeting"),
                            ("RIGHTS_ISSUE", "Rights Issue"),
                            ("EARNINGS", "Earnings Release"),
                            ("EX_DIVIDEND", "Ex-Dividend Date"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_date",
                    models.DateField(
                        help_text="The date the action occurs/takes effect."
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_actions",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["event_date"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "event_date"],
                        name="corporate_a_instrum_e6b482_idx",
                    )
                ],
            },
        ),
    ]
