# Generated by Django 5.2.16 on 2026-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementupload",
            name="broker",
            field=models.CharField(
                choices=[
                    ("IC_SECURITIES", "IC Securities"),
                    ("BLACKSTAR", "Black Star Advisors"),
                ],
                max_length=30,
            ),
        ),
    ]
