# Generated by Django 5.2.16 on 2026-07-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0002_alter_statementupload_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedtransaction",
            name="parse_notes",
            field=models.TextField(blank=True),
        ),
    ]
