# Generated by Django 5.2.16 on 2026-07-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("isin", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("listed_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="PriceIngestBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="csv_upload", max_length=20)),
                ("trade_date", models.DateField()),
                ("row_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                (
                    "raw_file",
                    models.FileField(blank=True, null=True, upload_to="price_ingest/"),
                ),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "open_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("csv_upload", "Manual CSV upload"),
                            ("scrape", "Automated scrape"),
                        ],
                        default="csv_upload",
                        max_length=20,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_bars",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "-trade_date"],
                        name="instruments_instrum_b4ec61_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "trade_date"), name="uniq_price_per_day"
                    )
                ],
            },
        ),
    ]
