# Generated by Django 5.2.16 on 2026-07-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("EQUITY", "Equity"),
                    ("FUND", "Fund"),
                    ("FIXED_INCOME", "Fixed Income"),
                ],
                default="EQUITY",
                max_length=20,
            ),
        ),
    ]
