# Generated by Django 5.2.16 on 2026-07-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0002_instrument_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricebar",
            name="turnover_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="GSE's 'Total Value Traded (GH¢)' — stored directly from the source rather than derived (volume × close), since it's VWAP-based.",
                max_digits=16,
                null=True,
            ),
        ),
    ]
