# Generated by Django 5.2.16 on 2026-07-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DividendRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_per_share",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "record_date",
                    models.DateField(help_text="Shareholders as of this date qualify."),
                ),
                ("ex_dividend_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("fiscal_year_note", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="instruments.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-ex_dividend_date"],
            },
        ),
        migrations.CreateModel(
            name="DividendReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_held", models.DecimalField(decimal_places=4, max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dividend_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="dividends.dividendrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "dividend_record"),
                        name="uniq_receipt_per_user_dividend",
                    )
                ],
            },
        ),
    ]
