# Generated by Django 5.2.16 on 2026-07-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("IC_SECURITIES", "IC Securities")], max_length=30
                    ),
                ),
                ("file", models.FileField(upload_to="statements/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARSING", "Parsing"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_ticker_text", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        max_length=4,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("trade_date", models.DateField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[("HIGH", "High"), ("LOW", "Low — needs review")],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                ("parse_notes", models.CharField(blank=True, max_length=255)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_excluded", models.BooleanField(default=False)),
                ("row_order", models.PositiveIntegerField(default=0)),
                (
                    "matched_instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instruments.instrument",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_rows",
                        to="statements.statementupload",
                    ),
                ),
            ],
            options={
                "ordering": ["row_order"],
            },
        ),
    ]
