from django.conf import settings
from django.db import models


class DividendRecord(models.Model):
    """Admin-entered: one per company per declared dividend."""

    instrument = models.ForeignKey("instruments.Instrument", on_delete=models.CASCADE, related_name="dividends")
    amount_per_share = models.DecimalField(max_digits=10, decimal_places=4)
    record_date = models.DateField(help_text="Shareholders as of this date qualify.")
    ex_dividend_date = models.DateField()
    payment_date = models.DateField(null=True, blank=True)
    fiscal_year_note = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-ex_dividend_date"]

    def __str__(self):
        return f"{self.instrument.ticker} — GHS {self.amount_per_share}/share ({self.ex_dividend_date})"


class DividendReceipt(models.Model):
    """
    Computed per-user record: user's held quantity as of record_date x
    amount_per_share. Generated by a service function when a DividendRecord
    is created/updated — not user-editable.
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="dividend_receipts")
    dividend_record = models.ForeignKey(DividendRecord, on_delete=models.CASCADE, related_name="receipts")
    quantity_held = models.DecimalField(max_digits=14, decimal_places=4)
    total_amount = models.DecimalField(max_digits=12, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "dividend_record"], name="uniq_receipt_per_user_dividend")
        ]

    def __str__(self):
        return f"{self.user} — {self.dividend_record}: GHS {self.total_amount}"
