# Generated by Django 5.2.16 on 2026-07-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0003_pricebar_turnover_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional official logo. GSE doesn't publish these, so most instruments fall back to a generated initials badge (see instruments/templatetags/instrument_avatar.py) — only upload one you can confirm is the real, current company mark.",
                null=True,
                upload_to="instrument_logos/",
            ),
        ),
    ]
