# Generated by Django 5.2.5 on 2025-08-19 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('instructor', models.CharField(blank=True, max_length=150, null=True)),
                ('venue', models.CharField(blank=True, max_length=150, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 = Unlimited capacity')),
                ('allowed_grades', models.ManyToManyField(related_name='activities', to='bookings.grade')),
            ],
            options={
                'ordering': ['day', 'name'],
                'unique_together': {('name', 'day')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=250)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.studentprofile')),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('student', 'day')},
            },
        ),
    ]
