# Generated by Django 5.2.5 on 2025-08-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default='12:45', max_length=50),
            preserve_default=False,
        ),
    ]
