# Generated by Django 5.2.5 on 2025-08-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
