# Generated by Django 5.2.16 on 2026-07-23 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("COMPANY", "Company"),
                            ("REGULATORY", "Regulatory"),
                            ("ECONOMY", "Economy"),
                            ("GSE", "GSE Announcements"),
                            ("OTHER", "Other"),
                        ],
                        default="MARKET",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="news/%Y/%m/")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short teaser shown on the News list card. Falls back to the start of the body if left blank.",
                        max_length=300,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the original source, if this summarizes one.",
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
