# Generated by Django 5.2.16 on 2026-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("office_address", models.CharField(blank=True, max_length=255)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                (
                    "default_meta_title",
                    models.CharField(
                        blank=True,
                        default="SikaTrack — GSE Portfolio Tracker",
                        max_length=70,
                    ),
                ),
                (
                    "default_meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Shown in search results and social link previews when a page doesn't set its own.",
                        max_length=160,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, help_text="e.g. G-XXXXXXXXXX", max_length=30
                    ),
                ),
                (
                    "adsense_client_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ca-pub-1234567890123456 — leave blank to show no ads.",
                        max_length=30,
                    ),
                ),
                (
                    "adsense_sidebar_slot_id",
                    models.CharField(
                        blank=True,
                        help_text="Ad unit slot ID for the news sidebar placement.",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Overrides the SEO/social description. Falls back to the summary.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Overrides the page <title>/SEO title. Falls back to the article title.",
                max_length=70,
            ),
        ),
    ]
