# Generated by Django 5.2.16 on 2026-07-26 02:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_sitesettings_newsarticle_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
